name: muslim_prayer_times
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: "2.7.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/map.png