name: muslim_prayer_times
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: "2.7.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.7
  location_permissions: ^2.0.5
  location: ^3.0.2
  provider: ^4.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/map.png